tools:
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
filter:
    excluded_paths:
        - 'tests/*'
build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=translug-coverage-file
                coverage:
                    file: translug-coverage-file
                    format: clover